/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Main.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Grant Bacaltos
 */
public class Administrator extends javax.swing.JFrame {

    private static Administrator adminUI;
    private User u;
    /**
     * Creates new form Administrator
     */
    public Administrator(User u) {
        initComponents();
        this.u = u;
        this.LBLwelcome.setText("Welcome, " + u.getFname() + "!");
        this.LBLloggedas.setText(u.getUser_type());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LBLwelcome = new javax.swing.JTextField();
        LBLloggedas = new javax.swing.JTextField();
        BTNeditProfile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BTNschedule = new javax.swing.JButton();
        BTNmanageCurriculum = new javax.swing.JButton();
        BTNpolicies = new javax.swing.JButton();
        BTNmanageRegistration = new javax.swing.JButton();
        BTNmanageUsers = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Manage Users");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POOFS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LBLwelcome.setEditable(false);
        LBLwelcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBLwelcome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LBLwelcome.setText("Welcombelles!");

        LBLloggedas.setEditable(false);
        LBLloggedas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LBLloggedas.setText("Logged in as churvabelles.");

        BTNeditProfile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNeditProfile.setText("Edit Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNeditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLwelcome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLloggedas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLloggedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNeditProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("What would you like to do?");

        BTNschedule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNschedule.setText("Manage Schedule");
        BTNschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNscheduleActionPerformed(evt);
            }
        });

        BTNmanageCurriculum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNmanageCurriculum.setText("Manage Curriculum");
        BTNmanageCurriculum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmanageCurriculumActionPerformed(evt);
            }
        });

        BTNpolicies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNpolicies.setText("Manage Policies");
        BTNpolicies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpoliciesActionPerformed(evt);
            }
        });

        BTNmanageRegistration.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNmanageRegistration.setText("Manage Registration Requests");
        BTNmanageRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmanageRegistrationActionPerformed(evt);
            }
        });

        BTNmanageUsers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNmanageUsers.setText("Manage Users");
        BTNmanageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmanageUsersActionPerformed(evt);
            }
        });

        BTNlogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNlogout.setText("Logout");
        BTNlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNschedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNmanageCurriculum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNpolicies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNmanageRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(BTNmanageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNschedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNmanageCurriculum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNpolicies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNmanageRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNmanageUsers)
                .addGap(73, 73, 73)
                .addComponent(BTNlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNmanageRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmanageRegistrationActionPerformed
        ManageRegistration.start(u);
        this.stop();
    }//GEN-LAST:event_BTNmanageRegistrationActionPerformed

    private void BTNlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlogoutActionPerformed
        Login.start();
        this.stop();
    }//GEN-LAST:event_BTNlogoutActionPerformed

    private void BTNmanageCurriculumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmanageCurriculumActionPerformed
        JOptionPane.showMessageDialog( null, "Coming soon.");
    }//GEN-LAST:event_BTNmanageCurriculumActionPerformed

    private void BTNpoliciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpoliciesActionPerformed
        ManageConstraints.start(u);
        this.stop();
    }//GEN-LAST:event_BTNpoliciesActionPerformed

    private void BTNmanageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmanageUsersActionPerformed
        JOptionPane.showMessageDialog( null, "Coming soon.");
    }//GEN-LAST:event_BTNmanageUsersActionPerformed

    private void BTNscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNscheduleActionPerformed
        ManageSchedule.start(u);
        this.stop();
    }//GEN-LAST:event_BTNscheduleActionPerformed

    public static void start(User u) {
        adminUI = new Administrator(u);
        Main.Utility.centerFrame(adminUI);
        adminUI.setVisible(true);
    }
    
    public static void stop() {
        adminUI.dispose();
    }
    
    public static void hideUI() {
        adminUI.setVisible(false);
    }
    
    public static void unhideUI() {
        adminUI.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNeditProfile;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton BTNmanageCurriculum;
    private javax.swing.JButton BTNmanageRegistration;
    private javax.swing.JButton BTNmanageUsers;
    private javax.swing.JButton BTNpolicies;
    private javax.swing.JButton BTNschedule;
    private javax.swing.JTextField LBLloggedas;
    private javax.swing.JTextField LBLwelcome;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
