/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database.DB;
import Main.User;
import javax.swing.JFrame;

/**
 *
 * @author Grant Bacaltos
 */
public class RegistrationRequest extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationRequest
     */
    
    private User u;
    public RegistrationRequest(User u) {
        initComponents();
        this.u = u;
        LBLname.setText(u.getFname() + " " + u.getMname().charAt(0) + ". " + u.getLname());
        LBLtype.setText(u.getUser_type());
    }

    public static void main(String[] args) {
        JFrame j = new JFrame();
        j.getContentPane().add(new RegistrationRequest(DB.getUser("grant")));
        j.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BTNview = new javax.swing.JButton();
        LBLname = new javax.swing.JLabel();
        LBLtype = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        BTNview.setText("View Info");
        BTNview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNviewActionPerformed(evt);
            }
        });

        LBLname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBLname.setText("Name");

        LBLtype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LBLtype.setText("Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BTNview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLname, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LBLname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLtype))
            .addComponent(BTNview, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNviewActionPerformed
        Register.start(u);
        ManageRegistration.stop();
    }//GEN-LAST:event_BTNviewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNview;
    private javax.swing.JLabel LBLname;
    private javax.swing.JLabel LBLtype;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
